RM = RD /S /Q

BOOST_PACKAGE = boost_1_57_0.7z
BOOST_SRC = boost_1_57_0



all: boost

boost:
	cmd /c boost_init.bat
	cmd /c boost_init_success.bat

clean: boost.clean

boost.clean:
	$(RM) $(BOOST_SRC)




