
TESTDIR = ./test

all: TestQueue

TestQueue:
	cd $(TESTDIR); make
	@echo
	@echo "[log_tools::priority_queue] Test cases compiled successfully in '"`pwd`/$(TESTDIR)"/bin/'"

clean:
	cd $(TESTDIR); make clean
