RM = rm -rf
GDB := -g

TMP = ./link
ROOT = ../


override CFLAGS   += -Wall $(GDB)
override CXXFLAGS += -Wall $(GDB) -std=gnu++0x # win32: -std=std=c++11
override INCPATH  += -I$(ROOT) 



all: init TARGET

init:
	[ -d '$(TMP)' ] || mkdir $(TMP)

TARGET: $(TMP)/except.o

$(TMP)/%.o: %.c
	$(CC) $(CFLAGS) $(INCPATH) -c $< -o $@
$(TMP)/%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(STDLIB) $(INCPATH) -c $< -o $@

clean:
	$(RM) $(TMP)

